<?php

namespace Newestapps\Core\Transformers;

use App\User;
use League\Fractal\TransformerAbstract;
use App\Organizer;

/**
 * @package namespace App\Transformers;
 */
class CoreTransformer extends TransformerAbstract
{

    protected function item($data, $transformer, $resourceKey = null)
    {
        if ($data === null) {
            return null;
        }

        return parent::item($data, $transformer, $resourceKey); // TODO: Change the autogenerated stub
    }

    protected function collection($data, $transformer, $resourceKey = null)
    {
        if ($data === null) {
            return null;
        }

        return parent::collection($data, $transformer, $resourceKey); // TODO: Change the autogenerated stub
    }

}
